import type { Metadata } from "next";
import { TaskProvider } from "@/context/taskContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Taski",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TaskProvider>{children}</TaskProvider>
      </body>
    </html>
  );
}
